//Buscar items
export const SEARCH_ITEMS = 'SEARCH_ITEMS';
export const SEARCH_ITEMS_SUCCESS = 'SEARCH_ITEMS_SUCCCESS';
export const SEARCH_ITEMS_ERROR = 'SEARCH_ITEMS_ERROR';
//Detalle de item
export const FETCH_ITEM_DETAIL = 'FETCH_DETAIL_ITEM';
export const FETCH_ITEM_DETAIL_SUCCESS = 'FETCH_DETAIL_ITEM_SUCCESS';
export const FETCH_ITEM_DETAIL_ERROR = 'FETCH_DETAIL_ITEM_ERROR';